# -*- coding: utf-8 -*-
"""기말과제 연습 (파일)

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GdQ_zB0HppWh8jmHaK85qKfuMo3u64s9

# (실습) 파일

**기본 설정**

파일 저장 경로와 파일 서버 주소를 지정에 필요한 기본 설정을 지정한다.
"""


# 코드를 작성하세요.
from pathlib import Path
from urllib.request import urlretrieve
import os
### urllib모듈 -> request 라이브러리 -> urlretrieve 임포트
base_url="https://raw.githubusercontent.com/codingalzi/pybook/master/jupyter-book/data/"

def myWget(filename,base_url):
  file_url = base_url + filename ## 링크 + 가져올 파일의 이름
  data_path = Path() / "data"
  data_path.mkdir(parents=True,exist_ok=True)
  target_path = data_path / filename
  return urlretrieve(file_url,target_path) ## url/파일 , 지정 경로로 다운



def search_dir(filename):
  ### 하위 디렉토리 찾은 다음 하위 디렉토리에 파일이 있는지 확인
    current_dir = os.getcwd()
    list_dir=os.listdir()
    for item in list_dir:
      find_path = current_dir + "/" + item + "/" + filename
      try:
        with open(find_path,"r") as f:
          return find_path

      except:
        continue


def shopping(shop_file):
  shopped_file = search_dir(shop_file)
  shop_dict = {} # 생성할 사전 객체
  with open (shopped_file,"r") as f:
    for line in f:
      line= line.strip()
      if "원" in line:
        line = line.split(" ")
        shop_dict[line[0]]=line[1].replace('원',"")
    return shop_dict



def item_price(shop_file, item):
  item_dict=shopping(shop_file)
  return item_dict[item]
print(item_price("shopA.txt", '김치'))




def price_comparison(item):
 shop_A =int(item_price("shopA.txt",item))
 shop_B =int(item_price("shopB.txt",item))
 if shop_A > shop_B :
   return f"shop_A 가  {shop_A - shop_B} 원 더 저렴"
 if shop_B > shop_A :
   return f"shop_A 가 {shop_B - shop_A}  원 더 저렴"
 if shop_B == shop_A :
   return f"shop_A shop_B  {shop_B - shop_A} 로 동일"
