# -*- coding: utf-8 -*-
"""price.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vxOZ85ydPT3IyBSxjiqJI0lUcA8y7M-f

# (실습) 파일

**기본 설정**

파일 저장 경로와 파일 서버 주소를 지정에 필요한 기본 설정을 지정한다.
"""

from pathlib import Path
from urllib.request import urlretrieve

"""데이터가 저장된 텍스트 파일 서버 주소는 다음과 같다."""

base_url = "https://raw.githubusercontent.com/codingalzi/pybook/master/jupyter-book/data/"

"""현재 작업 디렉토리의 `data` 하위 디렉토리에 파일을 다운로드해서 저장할 준비를 한다."""

# 저장위치 지정과 생성
data_path = Path() / "data"
data_path.mkdir(parents=True, exist_ok=True)

"""`myWget()` 함수는 파일 서버에서 지정된 파일을 동일한 파일명으로 지정된 디렉토리에 저장한다."""

def myWget(filename):
    # 다운로드 대상 파일 경로
    file_url = base_url + filename

    # 저장 경로와 파일명
    target_path = data_path / filename

    return urlretrieve(file_url, target_path)

"""**쇼핑몰 파일 관련**

**문제 1**

`shopA.txt` 파일은 쇼핑몰A에서 판매하는 상품의 가격을 담고 있음을 확인해보자.
먼저 해당 파일을 다운로드 한다.
"""

myWget("shopA.txt")

"""이제 파일 전체 내용을 출력하는 코드를 작성하라.

힌트: `with-as` 명령문, `open()` 함수, `readlines()` 또는 `read()` 파일 메서드.
"""

# 코드를 작성하세요.
from pathlib import Path
from urllib.request import urlretrieve
base_url = "https://raw.githubusercontent.com/codingalzi/pybook/master/jupyter-book/data/"
data_path_a = Path() / "data-a"
data_path_a.mkdir(parents=True, exist_ok=True)
def myWget(filename):
  file_url = base_url + filename
  target_path = data_path_a / filename
  return urlretrieve(file_url,target_path)
data_info=myWget("shopA.txt")
data_path_1 =data_info[0]
with open(data_path_1,"r") as f:
  read_f =f.read()
  print(read_f)

"""**문제 2**

`shopA.txt` 파일의 내용을 확인하면, 오타가 있다. 
'오레ㄴ지' 를 '오렌지'로 변경한 후에
`shopA.txt` 파일을 열어 오타가 수정되었는지를 확인하여라.  

힌트: 파일의 `read()` 메서드, 문자열의 `replace()` 메서드

* 파일 읽기: `read()` 메서드 활용
"""

def replace_line_f(data_path,old_line,new_line):
  with open(data_path,"r") as fr:
    lines = fr.readlines()
  with open(data_path,"w") as fw:
    for line in lines:
      fw.write(line.replace(old_line,new_line,1))
  with open(data_path_1,"r") as f:
    print(f.read())

replace_line_f(data_path_1,"오레ㄴ지","오렌지")

"""* 오타 수정: `replace()` 문자열 메서드 활용"""

# 오타를 수정하는 코드를 작성하라.
def replace_line_f(data_path,old_line,new_line):
  with open(data_path,"r") as fr:
    lines = fr.readlines()
  with open(data_path,"w") as fw:
    for line in lines:
      fw.write(line.replace(old_line,new_line,1))
  with open(data_path_1,"r") as f:
    print(f.read())

replace_line_f(data_path_1,"오레ㄴ지","오렌지")

"""* 파일 저장"""

# 오타가 수정된 문자열을 파일로 저장하는 코드를 작성하라.
def replace_line_f(data_path,old_line,new_line):
  data_path_2=str(data_path_1).split(".")
  data_path_2[0]= data_path_2[0] +"_"+"modified"
  data_path_2=".".join(data_path_2)
  with open(data_path,"r") as fr:
    lines = fr.readlines()
  with open(data_path_2,"w") as fw:
    for line in lines:
      fw.write(line.replace(old_line,new_line,1))
  with open(data_path_2,"r") as fr2:
    lines_modified = fr2.readlines()
    for line in lines_modified:
      line_replaced = line.split()
      if old_line not in line and new_line in line:
          print(f"{old_line}가(이) 수정되어 {data_path_2} 에 {line.split()[0]}(으)로 수정되어 저장됨.") 
replace_line_f(data_path_1,"오레ㄴ지","오렌지")

"""* 파일 내용 확인"""

# 오타가 수정되었음을 확인하는 코드를 작성하라.
def replace_line_f(data_path,old_line,new_line):
  data_path_2=str(data_path_1).split(".")
  data_path_2[0]= data_path_2[0] +"_"+"modified"
  data_path_2=".".join(data_path_2)
  with open(data_path,"r") as fr:
    lines = fr.readlines()
  with open(data_path_2,"w") as fw:
    for line in lines:
      fw.write(line.replace(old_line,new_line,1))
  with open(data_path_2,"r") as fr2:
    lines_modified = fr2.readlines()
    for line in lines_modified:
      line_replaced = line.split()
      if old_line not in line and new_line in line:
          print(f"{old_line}가(이) 수정되어 {data_path_2} 에 {line.split()[0]}(으)로 수정되어 저장됨.") 
replace_line_f(data_path_1,"오레ㄴ지","오렌지")

"""**문제 3**

상품명과 가격을 키-값의 쌍으로 갖는 아래 모양의 딕셔너리를 만들어라.
단, 오타가 수정된 파일을 이용해야 한다.

```python
{'우유': 2540,
 '계란': 7480,
 '생수': 980,
 '짜장라면': 3220,
 '두부': 1450,
 '콩나물': 1680,
 '김': 5480,
 '닭고기': 5980,
 '식빵': 2480,
 '바나나': 4980,
 '오렌지': 990,
 '카레': 2480,
 '만두': 6980,
 '어묵': 7980,
 '참치': 11880,
 '김치': 7980,
 '간장': 10800}
```
"""

with open("data-a/shopA_modified.txt","r") as f:
  read_lines= f.readlines()
a=[]  
for item in read_lines:
  item=item.rstrip()
  a.append(item)
if '' in a:
  a.remove('')
new_lst={}
for item2 in a:
  if "원" in item2:  
    b=item2.split(" ")
    new_lst[b[0]]=b[1]


print(new_lst)

"""**문제 4**

`shopA.txt` 와 같이 상품명과 가격으로 이루어진 쇼핑 리스트가 포함된 파일의 이름을 입력받으면
상품명과 가격을 각각 키와 값으로 갖는 사전 객체를 반환하는 함수 `shopping()` 을 구현하라.

힌트: 문제 3을 해결하기 위해 작성한 코드를 이용한다.
"""

# 아래 코드를 완성하라.
import os
os.getcwd()
os.chdir("data-a")
def shopping(shop_file):
  a=[]
  with open(shop_file,"r") as f:
    read_lines=f.readlines()
  for item in read_lines:
    item=item.rstrip()
    a.append(item)
  if '' in a:
    a.remove('')
  shopped_dir={}
  for item2 in a:
    if "원" in item2:
      b=item2.split(" ")
      shopped_dir[b[0]]=b[1]
  return shopped_dir
shopping("shopA_modified.txt")

os.getcwd()

"""**문제 5**

쇼핑 리스트와 상품을 인자로 지정하면 상품의 가격을 반환하는 함수 `item_price()` 를 구현하라.

힌트: `shopping()` 함수를 이용한다.
"""

# 함수를 완성하라.

def item_price(shop_file, item):
  shopped_dir = shopping(shop_file)
  item_lst = shopped_dir.keys()
  if item in item_lst:
    return shopped_dir[item]
  else:
    return None  

print(item_price("shopA_modified.txt", '김치'))

"""**문제 6**

`shopB.txt` 파일은 쇼핑몰B에서 판매하는 상품의 가격을 담고 있으며,
`shopA.txt` 파일과 동일한 방식으로 다운로드할 수 있다.
"""

from pathlib import Path
from urllib.request import urlretrieve
base_url = "https://raw.githubusercontent.com/codingalzi/pybook/master/jupyter-book/data/"
data_path_a = Path()
data_path_a.mkdir(parents=True, exist_ok=True)
def myWget(filename):
  file_url = base_url + filename
  target_path = data_path_a / filename
  return urlretrieve(file_url,target_path)


myWget("shopB.txt")

"""사용자가 상품을 입력하면, 쇼핑몰A와 쇼핑몰B 중 어느 쇼핑몰에서 구입하는 것이 얼마나 저렴한지를 보여주는
함수 `price_comparison()`를 작성하라.
"""

# 코드를 완성하라.

def price_comparison(item):
 a=item_price("shopA_modified.txt", item)
 a=a.replace("원","")
 a=int(a)
 b=item_price("shopB.txt",item)
 b.replace("원","")
 b=b.replace("원","")
 b=int(b)
 if a > b:
  print(f"B가 더 저렴함.")
 elif a < b:
  print(f"A가 더 저렴함.")
 else:
  print("A나 B나 같음")
    
    
print(price_comparison('김치'))

"""**다이빙 기록 관련**

**문제 7**

[5미터 다이빙 기록 에서 등수를 확인하는 작업](https://codingalzi.github.io/pybook/files.html#sec-exp-diving-5m)과 
동일한 작업을 10미터 다이빙 기록에 대해 진행하라.
"""

from pathlib import Path
import os
from urllib.request import urlretrieve

data_path3= "/content/data-a"

def myWget(filename):
  file_url = base_url + filename

  target_path = data_path3 + "/" + filename

  return urlretrieve(file_url, target_path)
results_10m_path =myWget("results10m.txt")[0]
with open(results_10m_path,"r",encoding='utf-8') as f:
   a={}
   ten_lines= f.readlines()
   for line in ten_lines:
    if "." in line:
      name_score=line.rstrip().split("  ")
      a[name_score[0]] = name_score[1]
   a= sorted(a.items(),key=lambda x:x[1],reverse=True)     
for prize in range(3):
  print(f"{prize+1}등 {a[prize][0]}, {a[prize][1]} 점")

"""**문제 8**

5미터 다이빙 기록과 10미터 다이빙 기록의 합에 대해 등수를 확인하는 코드를 작성하라.
"""

# 코드를 작성하라.
myWget("results5m.txt") ## 5m 기록 불러오기
results_5m_path= myWget("results5m.txt")[0]
with open(results_5m_path,"r",encoding='utf-8') as f:
  a_5m = {}
  five_lines= f.readlines()
  for line in five_lines: ### 5m 기록에 대하여 등수 매기기
    if "." in line:
      name_score_5m=line.rstrip().split("  ")
      a_5m[name_score_5m[0]]=name_score_5m[1]
  a_5m= sorted(a_5m.items(),key=lambda x: x[1],reverse=True) 
sum_of_a_5m = sorted(a_5m) ## sorted 된 이름 에 맞춰 점수의 리스트 만들기
sum_5m=[float(x[1]) for x in sum_of_a_5m]
sum_of_a_10m= sorted(a) ## 위와 동일한 작업을 10m에 대해 수행
sum_10m=[float(x[1])for x in sum_of_a_10m]
sum_10m_5m=[sum_5m[i] + sum_10m[i] for i in range(len(sum_5m))] ## 점수의 합의 리스트 만들기
dict_sum={}
for i in range(len(a)):
  dict_sum[sorted(a)[i][0]] = sum_10m_5m[i] ### sorted(a) 에 있는 이름의 기준으로 점수의 합의 사전 만들기
dict_sum_sorted=sorted(dict_sum.items(),key=lambda x: x[1],reverse=True)
for prize in range(3): ## 등수 3등까지 매기기
  print(f"{dict_sum_sorted[prize][0]} {dict_sum_sorted[prize][1]} 점으로 {prize+1}등")

""